# Generated by Django 2.2.6 on 2019-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
