# Generated by Django 2.2.6 on 2019-11-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0006_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='profile_bg',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
