# Generated by Django 2.2.6 on 2020-09-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
