# Generated by Django 2.2.6 on 2020-12-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0009_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nice.Category'),
        ),
    ]
