# Generated by Django 2.2.6 on 2020-12-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0011_auto_20201209_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
